### ISSUE TITLE
不支持汉字

### ISSUE THREAD

**Issue by YDX-2147483647** [YDX-2147483647/best-of-bits#5]
**Describe the issue:**

可能汉字被滤掉了？

https://github.com/best-of-lists/best-of-generator/blob/a0c6d8a37b57e5cfe8a6d684ac312605d94bbedc/src/best_of/utils.py#L36-L56

best-of-lists/best-of-generator#61

**Comment by YDX-2147483647** [comment]
best-of-lists/best-of-generator#62 引入了`ascii_description`。

**Comment by YDX-2147483647** [comment]
> Copied from https://github.com/best-of-lists/best-of-generator/pull/62#issuecomment-1503626000

1. I [forked the update-action repo](https://github.com/YDX-2147483647/best-of-update-action/commit/1c4d0457c6a49d5d01e4299066c35c1b47a6eb7a), and let `pip` [install from GitHub](https://pip.pypa.io/en/stable/topics/vcs-support/) directly.

2. Edit `.github/workflows/update-best-of-list.yml` in my own repo:

   ```yaml
   - name: update-best-of-list
     # uses: best-of-lists/best-of-update-action@v0.8.5
     uses: YDX-2147483647/best-of-update-action@ascii-description
   ```

3. Go to Actions in my own repo, run the workflow manually.
