### ISSUE TITLE
跳过 best-of-update-action 直接调用 best-of

### ISSUE THREAD

**Issue by YDX-2147483647** [YDX-2147483647/best-of-bits#90]
https://github.com/best-of-lists/best-of-update-action/compare/main...YDX-2147483647:best-of-update-action:best-of-bits 没有实质性更改，直接调用 best-of 即可。

```yaml
      - name: install best-of-generator
        run: pip install "best-of @ git+https://github.com/YDX-2147483647/best-of-generator.git@best-of-bits"
      - name: update-best-of-list
        run: best-of generate projects.yaml --github-key=${{ secrets.GITHUB_TOKEN }} --libraries-key=${{ secrets.LIBRARIES_KEY }} …
```

### Discussed in https://github.com/YDX-2147483647/best-of-bits/discussions/89

<div type='discussions-op-text'>

<sup>Originally posted by **YDX-2147483647** July 28, 2023</sup>
https://github.com/mkdocs/catalog/issues/91

https://github.com/mkdocs/mkdocs/releases/tag/1.5.0

- > we want all projects here, not just "best"

- 可参考那边的修改方式。 https://github.com/mkdocs/catalog/pull/94/files https://github.com/best-of-lists/best-of-generator/compare/main...mkdocs:best-of-generator:main

  best-of-lists/best-of-update-action 不需要，可以直接运行命令。
</div>
